version: '3.8'

services:
  redis_indexer:
    command: [redis-server, --appendonly, 'yes']
    image: redis:6.2.6
  indexer:
    image: ghcr.io/zkbob/zkbob-relayer:${RELAYER_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.relayer
    command: yarn run start:indexer:prod
    volumes:
      - ./zp-relayer/params:/app/zp-relayer/params/
    env_file: ./zp-relayer/indexer.env
    environment:
      - INDEXER_PORT=80
      - COMMON_REDIS_URL=redis_indexer:6379
    ports:
      - 8000:80
    depends_on:
      - redis_indexer
  redis_relayer:
    command: [redis-server, --appendonly, 'yes']
    image: redis:6.2.6
  relayer:
    image: ghcr.io/zkbob/zkbob-relayer:${RELAYER_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.relayer
    volumes:
      - ./zp-relayer/params:/app/zp-relayer/params/
    env_file: ./zp-relayer/relayer-decentralized.env
    environment:
      - RELAYER_PORT=80
      - RELAYER_PROVER_URL=http://commitment_watcher:80
      - COMMON_INDEXER_URL=http://indexer:80
      - COMMON_REDIS_URL=redis_relayer:6379
    ports:
      - 8001:80
    depends_on:
      - redis_relayer
  redis_prover:
    command: [redis-server, --appendonly, 'yes']
    image: redis:6.2.6
  commitment_watcher:
    image: ghcr.io/zkbob/zkbob-relayer:${RELAYER_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.relayer
    command: yarn run start:commitment-watcher:prod
    volumes:
      - ./zp-relayer/params:/app/zp-relayer/params/
    env_file: ./zp-relayer/commitment-watcher.env
    environment:
      - COMMITMENT_WATCHER_PORT=80
      - COMMON_INDEXER_URL=http://indexer:80
      - COMMON_REDIS_URL=redis_prover:6379
    ports:
      - 8002:80
    depends_on:
      - redis_prover
