version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache-cli
    command: >
      --deterministic
      --gasLimit 20000000
      --allowUnlimitedContractSize
      --networkId 1337
      --chainId 1337
    ports:
      - 8545:8545
  contracts:
    image: lok52/zp-contracts:latest
  verifier:
    image: lok52/verifier:latest
    build:
      context: ./docker
      dockerfile: Dockerfile.verifier
  redis:
    command: [redis-server, --appendonly, 'yes']
    image: redis:6.2.6
    ports:
      - 6379:6379
  relayer:
    build:
      context: .
      dockerfile: docker/Dockerfile.relayer
    volumes:
      - relayer_tree:/app/tree.db
      - relayer_txs:/app/txs.db
      - $PARAMS_PATH:/app/zp-relayer/params/
    env_file: ./zp-relayer/relayer.env
    ports:
      - 8000:8000
  watcher:
    build:
      context: .
      dockerfile: docker/Dockerfile.relayer
    command: yarn run start:direct-deposit-watcher:prod
    env_file: ./zp-relayer/watcher.env
volumes:
  relayer_tree:
  relayer_txs:
