version: "3.9"

services:
  redis:
    command: [redis-server, --appendonly, 'yes']
    image: redis:6.2.6
  relayer:
    image: ghcr.io/zkbob/zkbob-relayer:latest
    depends_on:
      - redis
    env_file: zp-relayer/.env
    volumes:
      - $PARAMS_PATH:/app/zp-relayer/params/
      - relayer_optimistic_tree:/app/zp-relayer/optimisticTree.db
      - relayer_optimistic_txs:/app/zp-relayer/optimisticTxs.db
      - relayer_tree:/app/zp-relayer/poolTree.db
      - relayer_txs:/app/zp-relayer/poolTxs.db
    expose:
      - 80
networks:
  default:
    external: true
    name: zkbob

volumes:
  relayer_optimistic_tree:
  relayer_optimistic_txs:
  relayer_tree:
  relayer_txs:
